ay

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -439,20 +439,20 @@ jobs:
       #       export BACKEND_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
       #       export API_URL="http://${BACKEND_IP}:3030"
       #       echo "API_URL = ${API_URL}"
-      - run:
-          name:  Backend Smoke test
-          command:  |
-            BACKEND_IP=$(aws ec2 describe-instances \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
-            export API_URL=http://${BACKEND_IP}:3030
-            echo ${API_URL}
-            if curl -s --head $API_URL/api/status
-            then
-              exit 0
-            else
-              exit 1
-            fi
+      # - run:
+      #     name:  Backend Smoke test
+      #     command:  |
+      #       BACKEND_IP=$(aws ec2 describe-instances \
+      #         --query 'Reservations[*].Instances[*].PublicIpAddress' \
+      #         --output text)
+      #       export API_URL=http://${BACKEND_IP}:3030
+      #       echo ${API_URL}
+      #       if curl -s --head $API_URL/api/status
+      #       then
+      #         exit 0
+      #       else
+      #         exit 1
+      #       fi
 
       
             
@@ -570,5 +570,5 @@ workflows:
           requires: [deploy-backend, deploy-frontend]
       - cloudfront-update:
           requires: [smoke-test]
-      - cleanup:
-          requires: [cloudfront-update]
+      # - cleanup:
+      #     requires: [cloudfront-update]
